services:
  app:
    container_name: app
    image: ${PROD_IMAGE_NAME}
    ports:
      - ${PORT}:8000
    env_file:
      - .env.prod
    environment:
      - PYTHONPATH=/workspace
    depends_on:
      - db
    volumes:
      - ./app:/workspace/app
      - /workspace/.venv
    command: sh -c "uv run python manage.py migrate && uv run gunicorn app.config.wsgi:application --bind 0.0.0.0:8000"
    
  db:
    container_name: db
    image: postgres:15
    ports:
      - 5432:5432
    env_file:
      - .env.prod
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: